(cl:defpackage mrp_action-msg
  (:use )
  (:export
   "<CUP_NAVIGATORACTION>"
   "CUP_NAVIGATORACTION"
   "<CUP_NAVIGATORACTIONFEEDBACK>"
   "CUP_NAVIGATORACTIONFEEDBACK"
   "<CUP_NAVIGATORACTIONGOAL>"
   "CUP_NAVIGATORACTIONGOAL"
   "<CUP_NAVIGATORACTIONRESULT>"
   "CUP_NAVIGATORACTIONRESULT"
   "<CUP_NAVIGATORFEEDBACK>"
   "CUP_NAVIGATORFEEDBACK"
   "<CUP_NAVIGATORGOAL>"
   "CUP_NAVIGATORGOAL"
   "<CUP_NAVIGATORRESULT>"
   "CUP_NAVIGATORRESULT"
  ))

