; Auto-generated. Do not edit!


(cl:in-package mob_rob_17_msgs-msg)


;//! \htmlinclude AcceptCupGoal.msg.html

(cl:defclass <AcceptCupGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass AcceptCupGoal (<AcceptCupGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <AcceptCupGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'AcceptCupGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name mob_rob_17_msgs-msg:<AcceptCupGoal> is deprecated: use mob_rob_17_msgs-msg:AcceptCupGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <AcceptCupGoal>) ostream)
  "Serializes a message object of type '<AcceptCupGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <AcceptCupGoal>) istream)
  "Deserializes a message object of type '<AcceptCupGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<AcceptCupGoal>)))
  "Returns string type for a message object of type '<AcceptCupGoal>"
  "mob_rob_17_msgs/AcceptCupGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'AcceptCupGoal)))
  "Returns string type for a message object of type 'AcceptCupGoal"
  "mob_rob_17_msgs/AcceptCupGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<AcceptCupGoal>)))
  "Returns md5sum for a message object of type '<AcceptCupGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'AcceptCupGoal)))
  "Returns md5sum for a message object of type 'AcceptCupGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<AcceptCupGoal>)))
  "Returns full string definition for message of type '<AcceptCupGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# -------------- Goal --------------~%#   No information required.~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'AcceptCupGoal)))
  "Returns full string definition for message of type 'AcceptCupGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# -------------- Goal --------------~%#   No information required.~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <AcceptCupGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <AcceptCupGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'AcceptCupGoal
))
