; Auto-generated. Do not edit!


(cl:in-package mob_rob_17_msgs-msg)


;//! \htmlinclude DeliverCupGoal.msg.html

(cl:defclass <DeliverCupGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass DeliverCupGoal (<DeliverCupGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DeliverCupGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DeliverCupGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name mob_rob_17_msgs-msg:<DeliverCupGoal> is deprecated: use mob_rob_17_msgs-msg:DeliverCupGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DeliverCupGoal>) ostream)
  "Serializes a message object of type '<DeliverCupGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DeliverCupGoal>) istream)
  "Deserializes a message object of type '<DeliverCupGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DeliverCupGoal>)))
  "Returns string type for a message object of type '<DeliverCupGoal>"
  "mob_rob_17_msgs/DeliverCupGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DeliverCupGoal)))
  "Returns string type for a message object of type 'DeliverCupGoal"
  "mob_rob_17_msgs/DeliverCupGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DeliverCupGoal>)))
  "Returns md5sum for a message object of type '<DeliverCupGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DeliverCupGoal)))
  "Returns md5sum for a message object of type 'DeliverCupGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DeliverCupGoal>)))
  "Returns full string definition for message of type '<DeliverCupGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# -------------- Goal --------------~%#   No information required.~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DeliverCupGoal)))
  "Returns full string definition for message of type 'DeliverCupGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# -------------- Goal --------------~%#   No information required.~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DeliverCupGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DeliverCupGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'DeliverCupGoal
))
