; Auto-generated. Do not edit!


(cl:in-package mob_rob_17_msgs-msg)


;//! \htmlinclude DeliverCupResult.msg.html

(cl:defclass <DeliverCupResult> (roslisp-msg-protocol:ros-message)
  ((result_code
    :reader result_code
    :initarg :result_code
    :type cl:fixnum
    :initform 0))
)

(cl:defclass DeliverCupResult (<DeliverCupResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DeliverCupResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DeliverCupResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name mob_rob_17_msgs-msg:<DeliverCupResult> is deprecated: use mob_rob_17_msgs-msg:DeliverCupResult instead.")))

(cl:ensure-generic-function 'result_code-val :lambda-list '(m))
(cl:defmethod result_code-val ((m <DeliverCupResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader mob_rob_17_msgs-msg:result_code-val is deprecated.  Use mob_rob_17_msgs-msg:result_code instead.")
  (result_code m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DeliverCupResult>) ostream)
  "Serializes a message object of type '<DeliverCupResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'result_code)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'result_code)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DeliverCupResult>) istream)
  "Deserializes a message object of type '<DeliverCupResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'result_code)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'result_code)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DeliverCupResult>)))
  "Returns string type for a message object of type '<DeliverCupResult>"
  "mob_rob_17_msgs/DeliverCupResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DeliverCupResult)))
  "Returns string type for a message object of type 'DeliverCupResult"
  "mob_rob_17_msgs/DeliverCupResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DeliverCupResult>)))
  "Returns md5sum for a message object of type '<DeliverCupResult>"
  "a328be338a7a89d3b5bba0d2781350c3")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DeliverCupResult)))
  "Returns md5sum for a message object of type 'DeliverCupResult"
  "a328be338a7a89d3b5bba0d2781350c3")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DeliverCupResult>)))
  "Returns full string definition for message of type '<DeliverCupResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# ------------ Result --------------~%#   Whether cup was successfully grasped from the mobile platform~%#   and delivered to the user or which kind of failure~%#   occurred.~%#   Error codes:~%#     200 Success.~%#     301 Cup not reachable.~%#     302 Mobile platform not reachable.~%#     401 Cup not found.~%#     402 Mobile platform not found.~%#     500 Path planning failed.~%#     600 Unknown.~%~%uint16 result_code~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DeliverCupResult)))
  "Returns full string definition for message of type 'DeliverCupResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# ------------ Result --------------~%#   Whether cup was successfully grasped from the mobile platform~%#   and delivered to the user or which kind of failure~%#   occurred.~%#   Error codes:~%#     200 Success.~%#     301 Cup not reachable.~%#     302 Mobile platform not reachable.~%#     401 Cup not found.~%#     402 Mobile platform not found.~%#     500 Path planning failed.~%#     600 Unknown.~%~%uint16 result_code~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DeliverCupResult>))
  (cl:+ 0
     2
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DeliverCupResult>))
  "Converts a ROS message object to a list"
  (cl:list 'DeliverCupResult
    (cl:cons ':result_code (result_code msg))
))
