; Auto-generated. Do not edit!


(cl:in-package mob_rob_17_msgs-msg)


;//! \htmlinclude NavigateCupResult.msg.html

(cl:defclass <NavigateCupResult> (roslisp-msg-protocol:ros-message)
  ((result_code
    :reader result_code
    :initarg :result_code
    :type cl:fixnum
    :initform 0))
)

(cl:defclass NavigateCupResult (<NavigateCupResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <NavigateCupResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'NavigateCupResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name mob_rob_17_msgs-msg:<NavigateCupResult> is deprecated: use mob_rob_17_msgs-msg:NavigateCupResult instead.")))

(cl:ensure-generic-function 'result_code-val :lambda-list '(m))
(cl:defmethod result_code-val ((m <NavigateCupResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader mob_rob_17_msgs-msg:result_code-val is deprecated.  Use mob_rob_17_msgs-msg:result_code instead.")
  (result_code m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <NavigateCupResult>) ostream)
  "Serializes a message object of type '<NavigateCupResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'result_code)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'result_code)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <NavigateCupResult>) istream)
  "Deserializes a message object of type '<NavigateCupResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'result_code)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'result_code)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<NavigateCupResult>)))
  "Returns string type for a message object of type '<NavigateCupResult>"
  "mob_rob_17_msgs/NavigateCupResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'NavigateCupResult)))
  "Returns string type for a message object of type 'NavigateCupResult"
  "mob_rob_17_msgs/NavigateCupResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<NavigateCupResult>)))
  "Returns md5sum for a message object of type '<NavigateCupResult>"
  "a328be338a7a89d3b5bba0d2781350c3")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'NavigateCupResult)))
  "Returns md5sum for a message object of type 'NavigateCupResult"
  "a328be338a7a89d3b5bba0d2781350c3")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<NavigateCupResult>)))
  "Returns full string definition for message of type '<NavigateCupResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# ------------ Result --------------~%#   Whether navigation was completed successfully~%#   or failed.~%#   Error codes:~%#   Error codes:~%#     200 Success.~%#     300 Navigation failed~%~%uint16 result_code~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'NavigateCupResult)))
  "Returns full string definition for message of type 'NavigateCupResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# ------------ Result --------------~%#   Whether navigation was completed successfully~%#   or failed.~%#   Error codes:~%#   Error codes:~%#     200 Success.~%#     300 Navigation failed~%~%uint16 result_code~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <NavigateCupResult>))
  (cl:+ 0
     2
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <NavigateCupResult>))
  "Converts a ROS message object to a list"
  (cl:list 'NavigateCupResult
    (cl:cons ':result_code (result_code msg))
))
