; Auto-generated. Do not edit!


(cl:in-package mob_rob_17_msgs-msg)


;//! \htmlinclude NavigateCupGoal.msg.html

(cl:defclass <NavigateCupGoal> (roslisp-msg-protocol:ros-message)
  ((destination
    :reader destination
    :initarg :destination
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass NavigateCupGoal (<NavigateCupGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <NavigateCupGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'NavigateCupGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name mob_rob_17_msgs-msg:<NavigateCupGoal> is deprecated: use mob_rob_17_msgs-msg:NavigateCupGoal instead.")))

(cl:ensure-generic-function 'destination-val :lambda-list '(m))
(cl:defmethod destination-val ((m <NavigateCupGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader mob_rob_17_msgs-msg:destination-val is deprecated.  Use mob_rob_17_msgs-msg:destination instead.")
  (destination m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <NavigateCupGoal>) ostream)
  "Serializes a message object of type '<NavigateCupGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'destination) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <NavigateCupGoal>) istream)
  "Deserializes a message object of type '<NavigateCupGoal>"
    (cl:setf (cl:slot-value msg 'destination) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<NavigateCupGoal>)))
  "Returns string type for a message object of type '<NavigateCupGoal>"
  "mob_rob_17_msgs/NavigateCupGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'NavigateCupGoal)))
  "Returns string type for a message object of type 'NavigateCupGoal"
  "mob_rob_17_msgs/NavigateCupGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<NavigateCupGoal>)))
  "Returns md5sum for a message object of type '<NavigateCupGoal>"
  "f0a072d25c34fd10f54870044e6eacdc")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'NavigateCupGoal)))
  "Returns md5sum for a message object of type 'NavigateCupGoal"
  "f0a072d25c34fd10f54870044e6eacdc")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<NavigateCupGoal>)))
  "Returns full string definition for message of type '<NavigateCupGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# -------------- Goal --------------~%#   Where to navigate:~%#     True = navigate to cup acceptor (group 1)~%#     False = navigate to cup deliverer (group 3)~%~%bool destination~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'NavigateCupGoal)))
  "Returns full string definition for message of type 'NavigateCupGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# -------------- Goal --------------~%#   Where to navigate:~%#     True = navigate to cup acceptor (group 1)~%#     False = navigate to cup deliverer (group 3)~%~%bool destination~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <NavigateCupGoal>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <NavigateCupGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'NavigateCupGoal
    (cl:cons ':destination (destination msg))
))
