; Auto-generated. Do not edit!


(cl:in-package mob_rob_17_msgs-msg)


;//! \htmlinclude TransportCupResult.msg.html

(cl:defclass <TransportCupResult> (roslisp-msg-protocol:ros-message)
  ((robot_id
    :reader robot_id
    :initarg :robot_id
    :type cl:fixnum
    :initform 0)
   (result_code
    :reader result_code
    :initarg :result_code
    :type cl:fixnum
    :initform 0))
)

(cl:defclass TransportCupResult (<TransportCupResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TransportCupResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TransportCupResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name mob_rob_17_msgs-msg:<TransportCupResult> is deprecated: use mob_rob_17_msgs-msg:TransportCupResult instead.")))

(cl:ensure-generic-function 'robot_id-val :lambda-list '(m))
(cl:defmethod robot_id-val ((m <TransportCupResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader mob_rob_17_msgs-msg:robot_id-val is deprecated.  Use mob_rob_17_msgs-msg:robot_id instead.")
  (robot_id m))

(cl:ensure-generic-function 'result_code-val :lambda-list '(m))
(cl:defmethod result_code-val ((m <TransportCupResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader mob_rob_17_msgs-msg:result_code-val is deprecated.  Use mob_rob_17_msgs-msg:result_code instead.")
  (result_code m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TransportCupResult>) ostream)
  "Serializes a message object of type '<TransportCupResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'robot_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'result_code)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'result_code)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TransportCupResult>) istream)
  "Deserializes a message object of type '<TransportCupResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'robot_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'result_code)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'result_code)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TransportCupResult>)))
  "Returns string type for a message object of type '<TransportCupResult>"
  "mob_rob_17_msgs/TransportCupResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TransportCupResult)))
  "Returns string type for a message object of type 'TransportCupResult"
  "mob_rob_17_msgs/TransportCupResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TransportCupResult>)))
  "Returns md5sum for a message object of type '<TransportCupResult>"
  "f648ffc63234acca95d2a4d4fc8979e4")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TransportCupResult)))
  "Returns md5sum for a message object of type 'TransportCupResult"
  "f648ffc63234acca95d2a4d4fc8979e4")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TransportCupResult>)))
  "Returns full string definition for message of type '<TransportCupResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# ------------ Result --------------~%#   Whether cup was successfully accepted from the user~%#   and placed on the mobile platform or which kind of failure~%#   occurred.~%#   Error codes:~%#     200 Success.~%#     301 Cup not reachable.~%#     302 Mobile platform not reachable.~%#     401 Cup not found.~%#     402 Mobile platform not found.~%#     500 Path planning failed.~%#     600 Unknown.~%~%uint8 robot_id~%uint16 result_code~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TransportCupResult)))
  "Returns full string definition for message of type 'TransportCupResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# ------------ Result --------------~%#   Whether cup was successfully accepted from the user~%#   and placed on the mobile platform or which kind of failure~%#   occurred.~%#   Error codes:~%#     200 Success.~%#     301 Cup not reachable.~%#     302 Mobile platform not reachable.~%#     401 Cup not found.~%#     402 Mobile platform not found.~%#     500 Path planning failed.~%#     600 Unknown.~%~%uint8 robot_id~%uint16 result_code~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TransportCupResult>))
  (cl:+ 0
     1
     2
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TransportCupResult>))
  "Converts a ROS message object to a list"
  (cl:list 'TransportCupResult
    (cl:cons ':robot_id (robot_id msg))
    (cl:cons ':result_code (result_code msg))
))
