// Generated by gencpp from file mob_rob_17_msgs/DeliverCupAction.msg
// DO NOT EDIT!


#ifndef MOB_ROB_17_MSGS_MESSAGE_DELIVERCUPACTION_H
#define MOB_ROB_17_MSGS_MESSAGE_DELIVERCUPACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mob_rob_17_msgs/DeliverCupActionGoal.h>
#include <mob_rob_17_msgs/DeliverCupActionResult.h>
#include <mob_rob_17_msgs/DeliverCupActionFeedback.h>

namespace mob_rob_17_msgs
{
template <class ContainerAllocator>
struct DeliverCupAction_
{
  typedef DeliverCupAction_<ContainerAllocator> Type;

  DeliverCupAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  DeliverCupAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::mob_rob_17_msgs::DeliverCupActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::mob_rob_17_msgs::DeliverCupActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::mob_rob_17_msgs::DeliverCupActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;




  typedef boost::shared_ptr< ::mob_rob_17_msgs::DeliverCupAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mob_rob_17_msgs::DeliverCupAction_<ContainerAllocator> const> ConstPtr;

}; // struct DeliverCupAction_

typedef ::mob_rob_17_msgs::DeliverCupAction_<std::allocator<void> > DeliverCupAction;

typedef boost::shared_ptr< ::mob_rob_17_msgs::DeliverCupAction > DeliverCupActionPtr;
typedef boost::shared_ptr< ::mob_rob_17_msgs::DeliverCupAction const> DeliverCupActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mob_rob_17_msgs::DeliverCupAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mob_rob_17_msgs::DeliverCupAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mob_rob_17_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'mob_rob_17_msgs': ['/home/seba/MRP/MRP-Praktikum/mrp_action_ws/devel/share/mob_rob_17_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mob_rob_17_msgs::DeliverCupAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mob_rob_17_msgs::DeliverCupAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mob_rob_17_msgs::DeliverCupAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mob_rob_17_msgs::DeliverCupAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mob_rob_17_msgs::DeliverCupAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mob_rob_17_msgs::DeliverCupAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mob_rob_17_msgs::DeliverCupAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f9591ce0d0424f3950df71fd1f7177f";
  }

  static const char* value(const ::mob_rob_17_msgs::DeliverCupAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f9591ce0d0424f3ULL;
  static const uint64_t static_value2 = 0x950df71fd1f7177fULL;
};

template<class ContainerAllocator>
struct DataType< ::mob_rob_17_msgs::DeliverCupAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mob_rob_17_msgs/DeliverCupAction";
  }

  static const char* value(const ::mob_rob_17_msgs::DeliverCupAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mob_rob_17_msgs::DeliverCupAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
DeliverCupActionGoal action_goal\n\
DeliverCupActionResult action_result\n\
DeliverCupActionFeedback action_feedback\n\
\n\
================================================================================\n\
MSG: mob_rob_17_msgs/DeliverCupActionGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
DeliverCupGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: mob_rob_17_msgs/DeliverCupGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# -------------- Goal --------------\n\
#   No information required.\n\
\n\
================================================================================\n\
MSG: mob_rob_17_msgs/DeliverCupActionResult\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
DeliverCupResult result\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalStatus\n\
GoalID goal_id\n\
uint8 status\n\
uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n\
uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n\
uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n\
                            #   and has since completed its execution (Terminal State)\n\
uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n\
uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n\
                            #    to some failure (Terminal State)\n\
uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n\
                            #    because the goal was unattainable or invalid (Terminal State)\n\
uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n\
                            #    and has not yet completed execution\n\
uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n\
                            #    but the action server has not yet confirmed that the goal is canceled\n\
uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n\
                            #    and was successfully cancelled (Terminal State)\n\
uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n\
                            #    sent over the wire by an action server\n\
\n\
#Allow for the user to associate a string with GoalStatus for debugging\n\
string text\n\
\n\
\n\
================================================================================\n\
MSG: mob_rob_17_msgs/DeliverCupResult\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
# ------------ Result --------------\n\
#   Whether cup was successfully grasped from the mobile platform\n\
#   and delivered to the user or which kind of failure\n\
#   occurred.\n\
#   Error codes:\n\
#     200 Success.\n\
#     301 Cup not reachable.\n\
#     302 Mobile platform not reachable.\n\
#     401 Cup not found.\n\
#     402 Mobile platform not found.\n\
#     500 Path planning failed.\n\
#     600 Unknown.\n\
\n\
uint16 result_code\n\
\n\
================================================================================\n\
MSG: mob_rob_17_msgs/DeliverCupActionFeedback\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
DeliverCupFeedback feedback\n\
\n\
================================================================================\n\
MSG: mob_rob_17_msgs/DeliverCupFeedback\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
# ---------- Feedback --------------\n\
#   Live feedback for debug purposes.\n\
string feedback\n\
";
  }

  static const char* value(const ::mob_rob_17_msgs::DeliverCupAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mob_rob_17_msgs::DeliverCupAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DeliverCupAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mob_rob_17_msgs::DeliverCupAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mob_rob_17_msgs::DeliverCupAction_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::mob_rob_17_msgs::DeliverCupActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::mob_rob_17_msgs::DeliverCupActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::mob_rob_17_msgs::DeliverCupActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOB_ROB_17_MSGS_MESSAGE_DELIVERCUPACTION_H
