// Generated by gencpp from file mob_rob_17_msgs/MotionExecutorGoal.msg
// DO NOT EDIT!


#ifndef MOB_ROB_17_MSGS_MESSAGE_MOTIONEXECUTORGOAL_H
#define MOB_ROB_17_MSGS_MESSAGE_MOTIONEXECUTORGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace mob_rob_17_msgs
{
template <class ContainerAllocator>
struct MotionExecutorGoal_
{
  typedef MotionExecutorGoal_<ContainerAllocator> Type;

  MotionExecutorGoal_()
    : goal_pose()
    , gripper_close_val(0.0)  {
    }
  MotionExecutorGoal_(const ContainerAllocator& _alloc)
    : goal_pose(_alloc)
    , gripper_close_val(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _goal_pose_type;
  _goal_pose_type goal_pose;

   typedef float _gripper_close_val_type;
  _gripper_close_val_type gripper_close_val;




  typedef boost::shared_ptr< ::mob_rob_17_msgs::MotionExecutorGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mob_rob_17_msgs::MotionExecutorGoal_<ContainerAllocator> const> ConstPtr;

}; // struct MotionExecutorGoal_

typedef ::mob_rob_17_msgs::MotionExecutorGoal_<std::allocator<void> > MotionExecutorGoal;

typedef boost::shared_ptr< ::mob_rob_17_msgs::MotionExecutorGoal > MotionExecutorGoalPtr;
typedef boost::shared_ptr< ::mob_rob_17_msgs::MotionExecutorGoal const> MotionExecutorGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mob_rob_17_msgs::MotionExecutorGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mob_rob_17_msgs::MotionExecutorGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mob_rob_17_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'mob_rob_17_msgs': ['/home/seba/MRP/MRP-Praktikum/mrp_action_ws/devel/share/mob_rob_17_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mob_rob_17_msgs::MotionExecutorGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mob_rob_17_msgs::MotionExecutorGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mob_rob_17_msgs::MotionExecutorGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mob_rob_17_msgs::MotionExecutorGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mob_rob_17_msgs::MotionExecutorGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mob_rob_17_msgs::MotionExecutorGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mob_rob_17_msgs::MotionExecutorGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "04f6519cc2b7bf795da0507c01848460";
  }

  static const char* value(const ::mob_rob_17_msgs::MotionExecutorGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x04f6519cc2b7bf79ULL;
  static const uint64_t static_value2 = 0x5da0507c01848460ULL;
};

template<class ContainerAllocator>
struct DataType< ::mob_rob_17_msgs::MotionExecutorGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mob_rob_17_msgs/MotionExecutorGoal";
  }

  static const char* value(const ::mob_rob_17_msgs::MotionExecutorGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mob_rob_17_msgs::MotionExecutorGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# -------------- Goal --------------\n\
geometry_msgs/Pose goal_pose\n\
float32 gripper_close_val\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::mob_rob_17_msgs::MotionExecutorGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mob_rob_17_msgs::MotionExecutorGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_pose);
      stream.next(m.gripper_close_val);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotionExecutorGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mob_rob_17_msgs::MotionExecutorGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mob_rob_17_msgs::MotionExecutorGoal_<ContainerAllocator>& v)
  {
    s << indent << "goal_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_pose);
    s << indent << "gripper_close_val: ";
    Printer<float>::stream(s, indent + "  ", v.gripper_close_val);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOB_ROB_17_MSGS_MESSAGE_MOTIONEXECUTORGOAL_H
