// Generated by gencpp from file mob_rob_17_msgs/NavigateCupGoal.msg
// DO NOT EDIT!


#ifndef MOB_ROB_17_MSGS_MESSAGE_NAVIGATECUPGOAL_H
#define MOB_ROB_17_MSGS_MESSAGE_NAVIGATECUPGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mob_rob_17_msgs
{
template <class ContainerAllocator>
struct NavigateCupGoal_
{
  typedef NavigateCupGoal_<ContainerAllocator> Type;

  NavigateCupGoal_()
    : destination(false)  {
    }
  NavigateCupGoal_(const ContainerAllocator& _alloc)
    : destination(false)  {
  (void)_alloc;
    }



   typedef uint8_t _destination_type;
  _destination_type destination;




  typedef boost::shared_ptr< ::mob_rob_17_msgs::NavigateCupGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mob_rob_17_msgs::NavigateCupGoal_<ContainerAllocator> const> ConstPtr;

}; // struct NavigateCupGoal_

typedef ::mob_rob_17_msgs::NavigateCupGoal_<std::allocator<void> > NavigateCupGoal;

typedef boost::shared_ptr< ::mob_rob_17_msgs::NavigateCupGoal > NavigateCupGoalPtr;
typedef boost::shared_ptr< ::mob_rob_17_msgs::NavigateCupGoal const> NavigateCupGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mob_rob_17_msgs::NavigateCupGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mob_rob_17_msgs::NavigateCupGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mob_rob_17_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'mob_rob_17_msgs': ['/home/seba/MRP/MRP-Praktikum/mrp_action_ws/devel/share/mob_rob_17_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mob_rob_17_msgs::NavigateCupGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mob_rob_17_msgs::NavigateCupGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mob_rob_17_msgs::NavigateCupGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mob_rob_17_msgs::NavigateCupGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mob_rob_17_msgs::NavigateCupGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mob_rob_17_msgs::NavigateCupGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mob_rob_17_msgs::NavigateCupGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f0a072d25c34fd10f54870044e6eacdc";
  }

  static const char* value(const ::mob_rob_17_msgs::NavigateCupGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf0a072d25c34fd10ULL;
  static const uint64_t static_value2 = 0xf54870044e6eacdcULL;
};

template<class ContainerAllocator>
struct DataType< ::mob_rob_17_msgs::NavigateCupGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mob_rob_17_msgs/NavigateCupGoal";
  }

  static const char* value(const ::mob_rob_17_msgs::NavigateCupGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mob_rob_17_msgs::NavigateCupGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# -------------- Goal --------------\n\
#   Where to navigate:\n\
#     True = navigate to cup acceptor (group 1)\n\
#     False = navigate to cup deliverer (group 3)\n\
\n\
bool destination\n\
";
  }

  static const char* value(const ::mob_rob_17_msgs::NavigateCupGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mob_rob_17_msgs::NavigateCupGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.destination);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavigateCupGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mob_rob_17_msgs::NavigateCupGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mob_rob_17_msgs::NavigateCupGoal_<ContainerAllocator>& v)
  {
    s << indent << "destination: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.destination);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOB_ROB_17_MSGS_MESSAGE_NAVIGATECUPGOAL_H
