// Generated by gencpp from file mob_rob_17_msgs/TransportCupFeedback.msg
// DO NOT EDIT!


#ifndef MOB_ROB_17_MSGS_MESSAGE_TRANSPORTCUPFEEDBACK_H
#define MOB_ROB_17_MSGS_MESSAGE_TRANSPORTCUPFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mob_rob_17_msgs
{
template <class ContainerAllocator>
struct TransportCupFeedback_
{
  typedef TransportCupFeedback_<ContainerAllocator> Type;

  TransportCupFeedback_()
    : feedback()  {
    }
  TransportCupFeedback_(const ContainerAllocator& _alloc)
    : feedback(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _feedback_type;
  _feedback_type feedback;




  typedef boost::shared_ptr< ::mob_rob_17_msgs::TransportCupFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mob_rob_17_msgs::TransportCupFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct TransportCupFeedback_

typedef ::mob_rob_17_msgs::TransportCupFeedback_<std::allocator<void> > TransportCupFeedback;

typedef boost::shared_ptr< ::mob_rob_17_msgs::TransportCupFeedback > TransportCupFeedbackPtr;
typedef boost::shared_ptr< ::mob_rob_17_msgs::TransportCupFeedback const> TransportCupFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mob_rob_17_msgs::TransportCupFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mob_rob_17_msgs::TransportCupFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mob_rob_17_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'mob_rob_17_msgs': ['/home/seba/MRP/MRP-Praktikum/mrp_action_ws/devel/share/mob_rob_17_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mob_rob_17_msgs::TransportCupFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mob_rob_17_msgs::TransportCupFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mob_rob_17_msgs::TransportCupFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mob_rob_17_msgs::TransportCupFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mob_rob_17_msgs::TransportCupFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mob_rob_17_msgs::TransportCupFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mob_rob_17_msgs::TransportCupFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c14cdf907e5c7c7fd47292add15660f0";
  }

  static const char* value(const ::mob_rob_17_msgs::TransportCupFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc14cdf907e5c7c7fULL;
  static const uint64_t static_value2 = 0xd47292add15660f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::mob_rob_17_msgs::TransportCupFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mob_rob_17_msgs/TransportCupFeedback";
  }

  static const char* value(const ::mob_rob_17_msgs::TransportCupFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mob_rob_17_msgs::TransportCupFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
# ---------- Feedback --------------\n\
#   Live feedback for debug purposes.\n\
string feedback\n\
\n\
";
  }

  static const char* value(const ::mob_rob_17_msgs::TransportCupFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mob_rob_17_msgs::TransportCupFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TransportCupFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mob_rob_17_msgs::TransportCupFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mob_rob_17_msgs::TransportCupFeedback_<ContainerAllocator>& v)
  {
    s << indent << "feedback: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOB_ROB_17_MSGS_MESSAGE_TRANSPORTCUPFEEDBACK_H
