// Generated by gencpp from file mrp_action/cup_navigatorGoal.msg
// DO NOT EDIT!


#ifndef MRP_ACTION_MESSAGE_CUP_NAVIGATORGOAL_H
#define MRP_ACTION_MESSAGE_CUP_NAVIGATORGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mrp_action
{
template <class ContainerAllocator>
struct cup_navigatorGoal_
{
  typedef cup_navigatorGoal_<ContainerAllocator> Type;

  cup_navigatorGoal_()
    : pose(0)  {
    }
  cup_navigatorGoal_(const ContainerAllocator& _alloc)
    : pose(0)  {
  (void)_alloc;
    }



   typedef int32_t _pose_type;
  _pose_type pose;




  typedef boost::shared_ptr< ::mrp_action::cup_navigatorGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mrp_action::cup_navigatorGoal_<ContainerAllocator> const> ConstPtr;

}; // struct cup_navigatorGoal_

typedef ::mrp_action::cup_navigatorGoal_<std::allocator<void> > cup_navigatorGoal;

typedef boost::shared_ptr< ::mrp_action::cup_navigatorGoal > cup_navigatorGoalPtr;
typedef boost::shared_ptr< ::mrp_action::cup_navigatorGoal const> cup_navigatorGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mrp_action::cup_navigatorGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mrp_action::cup_navigatorGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mrp_action

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'mrp_action': ['/home/seba/MRP/MRP-Praktikum/mrp_ws/devel/share/mrp_action/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mrp_action::cup_navigatorGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrp_action::cup_navigatorGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrp_action::cup_navigatorGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrp_action::cup_navigatorGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrp_action::cup_navigatorGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrp_action::cup_navigatorGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mrp_action::cup_navigatorGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d44f52d3d32c29788eac455c41de3a94";
  }

  static const char* value(const ::mrp_action::cup_navigatorGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd44f52d3d32c2978ULL;
  static const uint64_t static_value2 = 0x8eac455c41de3a94ULL;
};

template<class ContainerAllocator>
struct DataType< ::mrp_action::cup_navigatorGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mrp_action/cup_navigatorGoal";
  }

  static const char* value(const ::mrp_action::cup_navigatorGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mrp_action::cup_navigatorGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
int32 pose\n\
";
  }

  static const char* value(const ::mrp_action::cup_navigatorGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mrp_action::cup_navigatorGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cup_navigatorGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mrp_action::cup_navigatorGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mrp_action::cup_navigatorGoal_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    Printer<int32_t>::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MRP_ACTION_MESSAGE_CUP_NAVIGATORGOAL_H
