// Generated by gencpp from file mrp_action/cup_navigatorFeedback.msg
// DO NOT EDIT!


#ifndef MRP_ACTION_MESSAGE_CUP_NAVIGATORFEEDBACK_H
#define MRP_ACTION_MESSAGE_CUP_NAVIGATORFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mrp_action
{
template <class ContainerAllocator>
struct cup_navigatorFeedback_
{
  typedef cup_navigatorFeedback_<ContainerAllocator> Type;

  cup_navigatorFeedback_()
    : status()  {
    }
  cup_navigatorFeedback_(const ContainerAllocator& _alloc)
    : status(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _status_type;
  _status_type status;




  typedef boost::shared_ptr< ::mrp_action::cup_navigatorFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mrp_action::cup_navigatorFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct cup_navigatorFeedback_

typedef ::mrp_action::cup_navigatorFeedback_<std::allocator<void> > cup_navigatorFeedback;

typedef boost::shared_ptr< ::mrp_action::cup_navigatorFeedback > cup_navigatorFeedbackPtr;
typedef boost::shared_ptr< ::mrp_action::cup_navigatorFeedback const> cup_navigatorFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mrp_action::cup_navigatorFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mrp_action::cup_navigatorFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mrp_action

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'mrp_action': ['/home/seba/MRP/MRP-Praktikum/mrp_ws/devel/share/mrp_action/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mrp_action::cup_navigatorFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrp_action::cup_navigatorFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrp_action::cup_navigatorFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrp_action::cup_navigatorFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrp_action::cup_navigatorFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrp_action::cup_navigatorFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mrp_action::cup_navigatorFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "672ccc7edd3a5621529e608443618e1f";
  }

  static const char* value(const ::mrp_action::cup_navigatorFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x672ccc7edd3a5621ULL;
  static const uint64_t static_value2 = 0x529e608443618e1fULL;
};

template<class ContainerAllocator>
struct DataType< ::mrp_action::cup_navigatorFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mrp_action/cup_navigatorFeedback";
  }

  static const char* value(const ::mrp_action::cup_navigatorFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mrp_action::cup_navigatorFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback\n\
int32[] status\n\
\n\
";
  }

  static const char* value(const ::mrp_action::cup_navigatorFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mrp_action::cup_navigatorFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cup_navigatorFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mrp_action::cup_navigatorFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mrp_action::cup_navigatorFeedback_<ContainerAllocator>& v)
  {
    s << indent << "status[]" << std::endl;
    for (size_t i = 0; i < v.status.size(); ++i)
    {
      s << indent << "  status[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.status[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MRP_ACTION_MESSAGE_CUP_NAVIGATORFEEDBACK_H
