// Generated by gencpp from file mrp_action/cup_navigatorActionGoal.msg
// DO NOT EDIT!


#ifndef MRP_ACTION_MESSAGE_CUP_NAVIGATORACTIONGOAL_H
#define MRP_ACTION_MESSAGE_CUP_NAVIGATORACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <mrp_action/cup_navigatorGoal.h>

namespace mrp_action
{
template <class ContainerAllocator>
struct cup_navigatorActionGoal_
{
  typedef cup_navigatorActionGoal_<ContainerAllocator> Type;

  cup_navigatorActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  cup_navigatorActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::mrp_action::cup_navigatorGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;




  typedef boost::shared_ptr< ::mrp_action::cup_navigatorActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mrp_action::cup_navigatorActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct cup_navigatorActionGoal_

typedef ::mrp_action::cup_navigatorActionGoal_<std::allocator<void> > cup_navigatorActionGoal;

typedef boost::shared_ptr< ::mrp_action::cup_navigatorActionGoal > cup_navigatorActionGoalPtr;
typedef boost::shared_ptr< ::mrp_action::cup_navigatorActionGoal const> cup_navigatorActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mrp_action::cup_navigatorActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mrp_action::cup_navigatorActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mrp_action

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'mrp_action': ['/home/seba/MRP/MRP-Praktikum/mrp_ws/devel/share/mrp_action/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mrp_action::cup_navigatorActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrp_action::cup_navigatorActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrp_action::cup_navigatorActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrp_action::cup_navigatorActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrp_action::cup_navigatorActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrp_action::cup_navigatorActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mrp_action::cup_navigatorActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fb9572b6f9508306f55c7d4de25c21e3";
  }

  static const char* value(const ::mrp_action::cup_navigatorActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfb9572b6f9508306ULL;
  static const uint64_t static_value2 = 0xf55c7d4de25c21e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::mrp_action::cup_navigatorActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mrp_action/cup_navigatorActionGoal";
  }

  static const char* value(const ::mrp_action::cup_navigatorActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mrp_action::cup_navigatorActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
cup_navigatorGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: mrp_action/cup_navigatorGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
int32 pose\n\
";
  }

  static const char* value(const ::mrp_action::cup_navigatorActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mrp_action::cup_navigatorActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cup_navigatorActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mrp_action::cup_navigatorActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mrp_action::cup_navigatorActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::mrp_action::cup_navigatorGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MRP_ACTION_MESSAGE_CUP_NAVIGATORACTIONGOAL_H
