// Auto-generated. Do not edit!

// (in-package mob_rob_17_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class DeliverCupResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.result_code = null;
    }
    else {
      if (initObj.hasOwnProperty('result_code')) {
        this.result_code = initObj.result_code
      }
      else {
        this.result_code = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DeliverCupResult
    // Serialize message field [result_code]
    bufferOffset = _serializer.uint16(obj.result_code, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DeliverCupResult
    let len;
    let data = new DeliverCupResult(null);
    // Deserialize message field [result_code]
    data.result_code = _deserializer.uint16(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 2;
  }

  static datatype() {
    // Returns string type for a message object
    return 'mob_rob_17_msgs/DeliverCupResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'a328be338a7a89d3b5bba0d2781350c3';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    # ------------ Result --------------
    #   Whether cup was successfully grasped from the mobile platform
    #   and delivered to the user or which kind of failure
    #   occurred.
    #   Error codes:
    #     200 Success.
    #     301 Cup not reachable.
    #     302 Mobile platform not reachable.
    #     401 Cup not found.
    #     402 Mobile platform not found.
    #     500 Path planning failed.
    #     600 Unknown.
    
    uint16 result_code
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DeliverCupResult(null);
    if (msg.result_code !== undefined) {
      resolved.result_code = msg.result_code;
    }
    else {
      resolved.result_code = 0
    }

    return resolved;
    }
};

module.exports = DeliverCupResult;
